DynamicNotebook: fixed return_if_fail in non-void method insert_tab leading to a build error on macOS (#68)
DynamicNotebook.insert_tab returns an unsigned integer, but uses GLib.return_if_fail instead of the correct GLib.return_val_if_fail. Presumably this would only result in a warning on a native elementaryOS build, but on OS X with clang, this produces a compile error instead:

.../granite/build/lib/Widgets/DynamicNotebook.c:4159:2: error:
      non-void function 'granite_widgets_dynamic_notebook_insert_tab' should
      return a value [-Wreturn-type]
        g_return_if_fail (_tmp3_ < 0);

This error blocked granite from being included in Homebrew in the past; see https://github.com/Homebrew/homebrew-core/pull/1139.

Thanks to TingPing, baedert, and benwaffle in irc.gimp.net #gtk+ for help identifying the correct way to fix this bug.